### ISSUE TITLE
[BUG] No audio all of a sudden

### ISSUE THREAD

**Issue by johnybr99** [ananjaser1211/FloydQ_8890#41] opened 2020-04-23 14:56 UTC
**Describe the bug**
Audio is just gone for some reason.

**To Reproduce**
I don't know, it just randomly stopped working

**Expected behavior**
There should be audio 😅

**Smartphone (please complete the following information):**
 - Device: Galaxy S7e
 - Model: G935F
[log_dmesg.zip](https://github.com/ananjaser1211/FloydQ_8890/files/4523299/log_dmesg.zip)

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by ananjaser1211** [comment] 2020-04-24 01:07
Duplicate of #33

**Closed by ananjaser1211** 2020-04-24 01:07 UTC
Labels: duplicate
