### ISSUE TITLE
[BUG] After installing moro kernel phone doesn't wakeup after fully cahrged.

### ISSUE THREAD

**Issue by sandeepsp121** [ananjaser1211/FloydQ_8890#50] opened 2020-04-26 01:15 UTC
*after installing moro kernel phone went to deep sleep mode after putting it in to charger at night and didn't wake up when i try to press the power or center button. Then pressing  volume down and power button restart the phone. 
It also happened before this but then the phone wake up by pressing home button few time. Please note that at that time charger was plug out before fully charged the phone.
I am using moro kernel without using any specific changes in it.
V 8.1
My phone is s7 edge.

**Comment by SkylakeRyzen** [comment] 2020-04-26 02:15
Try to use default setting maybe you messed up with wrong configuration

**Comment by sandeepsp121** [comment] 2020-04-26 02:17
Yeah i am using default settings. Nothing changed as mention.

**Comment by ananjaser1211** [comment] 2020-04-26 05:24
Duplicate of #7 . forward reporting there. its the same issue

**Closed by ananjaser1211** 2020-04-26 05:24 UTC
